//
//  Organizations.swift
//  VolunteerAPP
//
//  Created by Arushi Sharma on 7/22/21.
//

import SwiftUI

struct Organization: Identifiable{
    let id = UUID()
    let imageName: String
    let title: String
    let typeOfOrganization: String
    let hours: String
    let phoneNumber: String
    let address: String
    let upcomingEvent: String
    let description: String
    let url: URL
}
struct OrganizationList {
    
    static let topTen = [
        Organization( imageName: "arch",
                     title: "ARCH (Austin Resource Center for the Homeless)",
                     typeOfOrganization: "Clothing, Shelter, Health Care, Food",
                     hours: "Open 24 Hours",
                     phoneNumber: "512-978-9920",
                     address: "500 East 7th Street, Austin, TX 78701",
                     upcomingEvent: "Please check out their website or call for more details!",
                     description: "The ARCH is designed to assess client needs, provide information on how and where to access services, and meet the basic emergency needs of homeless adults.",
                     url: URL (string:"https://goo.gl/maps/E1xodubeSZ4jSQ5N9")!),
        
        Organization( imageName: "goodwill",
                     title: "Goodwill Center: Riverside",
                     typeOfOrganization: "Clothing",
                     hours: "Mon-Sat: 9am-8pm, Sun: 10am-8pm",
                     phoneNumber: "512-389-0547",
                     address: "1819 S Pleasant Valley Rd Suite B, Austin, TX 78741",
                     upcomingEvent: " Cheaper clothing that can be purchased at the Goodwill Center! Also, GoodwilWorks program helps give out job training and employment services to lower income families",
                     description: "Check out Goodwill Works or shop at this center for clothing!",
                     url: URL (string:"https://goo.gl/maps/QhuipAcxcGiuF2WW9")!),
        
        Organization( imageName: "montopoliscenter",
                     title: "Montopolis Neighborhood Center",
                     typeOfOrganization: "Clothing, Food",
                     hours: "Mon-Sat: 9am-12pm, 1-5pm, Sun: Closed",
                     phoneNumber: "512-972-6650",
                     address: "1416 Montopolis Drive, Austin, TX 78741",
                     upcomingEvent: "Here are some ways the Montopolis Neighborhood Center can help for free: Access to basic services such as a food pantry, Social Services such as a clothes closet, Information with rent and utlity help, and several free services during special events.",
                     description: "They can help! Please use them if you need it.",
                     url: URL (string:"https://goo.gl/maps/jFoCYEjMPFiPYxjdA")!),
        
        Organization( imageName: "saneighborhoodcenter",
                     title: "South Austin Neighborhood Center",
                     typeOfOrganization: "Clothing, Food",
                     hours: "Call for appointment- Mon-Thurs: 8am-6pm and Friday: 8am-12pm",
                     phoneNumber: "512-972-6840",
                     address: "2508 Durwood Street, Austin, TX 78704",
                     upcomingEvent: "Here are some ways the South Austin Neighborhood Center can help for free: Basic services such as food pantry and bus passes, Health services such as checking blood pressure or pregnancy testing, and Social Services such as short term counseling and job help.",
                     description: "They can help! Please use them if you need it.",
                     url: URL (string:"https://goo.gl/maps/2bagxfohMjj7QAFd8")!),
        
        Organization( imageName: "baptistcenter",
                     title: "Baptist Community Center",
                     typeOfOrganization: "Clothing",
                     hours: "Mon-Friday: 8:30am —12:00pm to 1pm-5pm",
                     phoneNumber: "512- 478-7243",
                     address: "2000 East 2nd Street, Austin, TX 78702",
                     upcomingEvent: "Every Wednesday, the BCCM opens its sales room to offer good, gently worn clothing and other miscellaneous items at a reasonable cost.",
                     description: "This is based on availability, so please call the number if you need help!",
                     url: URL (string:"https://goo.gl/maps/7mZApmKstQzFFMq29")!),
        
        Organization( imageName: "gethsemane",
                     title: "Gethsemane Lutheran Church - Travis County",
                     typeOfOrganization: "Clothing",
                     hours: "Gethsemane Food Pantry & Clothes Closet Open on Tuesdays from 1:30-3:45 p.m. to distribute items to those in need.",
                     phoneNumber: "(512) 836-8560",
                     address: "200 W. Anderson Lane Austin, TX 78752",
                     upcomingEvent: "This church offers basic needs assistnace programs and is able to assist with cheaper/free clothing if needed through the Gethsemane Food Pantry & Clothes Closet.",
                     description: "This is based on availability, so please call the number if you need help!",
                     url: URL (string:"https://goo.gl/maps/A1RzqVPEDRN8tZ1s8")!),
        
        Organization( imageName: "dress4success",
                     title: "Dress for Success Austin",
                     typeOfOrganization: "Clothing",
                     hours: "Open on Tuesdays from 1:30-3:45 p.m. to distribute items to those in need.",
                     phoneNumber: "(512) 389-3723",
                     address: "701 Tillery Street Suite A5, Austin, TX 78702",
                     upcomingEvent: "This church offers basic needs assistnace programs and is able to assist with cheaper/free clothing if needed through the Gethsemane Food Pantry & Clothes Closet.",
                     description: "This is based on availability, so please call the number if you need help!",
                     url: URL (string:"https://goo.gl/maps/DcWkQd7AgjpXyjvr5")!),

        
        Organization( imageName: "manodecristo",
                     title: "Mano De Cristo",
                     typeOfOrganization: "Clothing, Food",
                     hours: "Food Pantry Hours: Monday - Friday: 8:00 a.m.-11:00 a.m. Clothes Closet Hours: Tuesday - Thursday: 8:00 a.m.-11:00 a.m.",
                     phoneNumber: "(512)-477-7454",
                     address: "4911 Harmon Avenue, Austin, TX 78751",
                     upcomingEvent: "This organization offers basic needs assistnace programs and is able to assist with cheape  clothing if needed through the Clothes Closet and Food Pantry",
                     description: "These services can be used once every three months based on avaibility. Please call! They can help!",
                     url: URL (string:"https://goo.gl/maps/C2FMyj9tJ7ghJjTP8")!),
        
        Organization( imageName: "mtzion",
                     title: "Greater Mt. Zion Church Community Assistance Center",
                     typeOfOrganization: "Clothing",
                     hours: "Every Tuesday and Thursday, from 10:00 a.m. - 4:00 p.m. Make an appointment",
                     phoneNumber: "(512) 478-7578",
                     address: "4301 Tannehill Ln, Austin, TX 78721",
                     upcomingEvent: "Clothing for work, school or a job interview is offered. They also have items for single moms such as carriages or strollers, shoes and notebooks for lower income students (as well as other free school supplies) and much more.",
                     description: "They can help! You can also email at:poverty@gmzaustin.org ",
                     url: URL (string:"https://goo.gl/maps/EUQAPzjCTTNPREZs5")!),
        
        Organization( imageName: "greaterhope",
                     title: "Greater HOPE Center",
                     typeOfOrganization: "Clothing",
                     hours: "Open Tuesdays and Thursdays 5:30–7:00PM and Saturdays 10:00-2:00.",
                     phoneNumber: "(512) 478-7578",
                     address: "4136 E. 12th Street Austin, Tx 78721",
                     upcomingEvent: "The Greater HOPE Center provides professional clothing, free of charge, to men and women transitioning back into the work force.",
                     description: "They can help! You can also email at:poverty@gmzaustin.org ",
                     url: URL (string:"https://goo.gl/maps/NzUaRLt984xRRZN46")!),
        
        Organization( imageName: "helpinghands",
                     title: "The Olivet Helping Hands Center",
                     typeOfOrganization: "Clothing, Food",
                     hours: "Food Giveaway, 2nd/4th Saturday,: 9am - 12noon ",
                     phoneNumber: " 512-472-2298",
                     address: "1161 San Bernard St. Austin TX 78702 ",
                     upcomingEvent: "The Helping Hands Center has grocery bags of nutritional food to pick up during the hours stated. They also have clothing based on avaiablility.",
                     description: "They can help! Please call for clothing if needed. ",
                     url: URL (string:"https://goo.gl/maps/ooDqG2xuS8oWeqPHA")!),
        
        Organization( imageName: "thriftland",
                     title: "ThriftLand",
                     typeOfOrganization: "Clothing",
                     hours: "Mon-Satur: 9am-6pm, Sun: 12-5pm",
                     phoneNumber: "(512) 326-1510",
                     address: "512 West Stassney Ln #107A, Austin, TX 78745",
                     upcomingEvent: "Thriftland has cheaper clothing for individuals.New day, new deal! Each day offers a huge discount in select departments throughout the store, on select color tags",
                     description: "They can help! Please call for clothing if needed. ",
                     url: URL (string:"https://goo.gl/maps/pmcd4oS37kYb7ZVf8")!),
        
        Organization( imageName: "michah6",
                     title: "Micah6Austin",
                     typeOfOrganization: "Clothing",
                     hours: "Saturdays 12:30 - 4:00 PM, Sundays 2:00 - 6:00 PM",
                     phoneNumber: "512-538-6332",
                     address: "2107 San Antonio Street Austin, TX 78705 ext. 206",
                     upcomingEvent: "The Micah 6 Street Youth program is a series of services provided for young adults 30 and younger who are street dependent. Computer labs, a hot, home cooked meal, snacks, basic clothing, TV, a laundry, and toiletries are provided.",
                     description: "They can help!",
                     url: URL (string:"https://goo.gl/maps/eTCvS8bD3wqknUgQ7")!),
        
        Organization( imageName: "westover",
                     title: "Westover Hills Church Of Christ",
                     typeOfOrganization: "Clothing, Food",
                     hours: "Mon-Thurs: 8am-5am, Sun: 9am-12:30pm, Drive-thru food pantry on Saturdays, 9 – 11 AM.",
                     phoneNumber: "(512) 345-6386",
                     address: "8332 Mesa Dr.Austin, TX 78759",
                     upcomingEvent: "Offers a clothing closet and while limited, may have rental and utility bill assistance for Travis County region. There are blankets for the homeless, free clothes for immigrants including Mexicans, baby supplies and more.",
                     description: "They can help!",
                     url: URL (string:"https://goo.gl/maps/iGyLn9mBL953Ebie9")!),
        
        Organization( imageName: "elbueno",
                     title: "El Buen Samaritano",
                     typeOfOrganization: "Health Care, Food",
                     hours: " ",
                     phoneNumber: "(512) 439-8900",
                     address: "7000 Woodhue Dr, Austin, TX 78745",
                     upcomingEvent: "El Buen provides comprehensive, integrated health and family services in a culturally appropriate environment. We offer a health home for individuals and families living in Travis County who are uninsured.",
                     description: "They can help!",
                     url: URL (string:"https://goo.gl/maps/ZkptjbUEvBPKqux99")!),
        
        Organization( imageName: "cddoyle",
                     title: "C.D. Doyle Free Healthcare Clinic",
                     typeOfOrganization: "HealthCare",
                     hours: "Sunday from 2:00 - 4:00 PM ",
                     phoneNumber: "(409) 571-9362",
                     address: "900 E 30th St # 314, Austin, TX 78705",
                     upcomingEvent: "The C.D. Doyle Clinic works to provide care for uninsured or underinsured patients until they can be seen at a more comprehensive clinic.",
                     description: "They can help!",
                     url: URL (string:"https://goo.gl/maps/T9Q4xyqAyqStgK8e8")!),
        
        Organization( imageName: "sunrise",
                     title: "Sunrise Homeless Navigation Center",
                     typeOfOrganization: "Health Care, Food, Clothing",
                     hours: "Mon-Friday: 9am-1pm",
                     phoneNumber: "(512) 522-1097",
                     address: "4430 Manchaca Rd, Austin, TX 78745",
                     upcomingEvent: "Services Offered: Mail, Food, Housing Assesment & Housing Naviagation, ID Help, Mental Health Support, Physicsl Healthcare Clinic, Telephone",
                     description: "Only donations requested! They can help!",
                     url: URL (string:"https://goo.gl/maps/D5x2vv5X2zHXHV616")!),
        
        Organization( imageName: "people's",
                     title: "People's Community Clinic",
                     typeOfOrganization: "Health Care",
                     hours: " ",
                     phoneNumber: "512-478-4939",
                     address: "2909 N Interstate Hwy 35, Austin, TX 78722",
                     upcomingEvent: "People’s adolescent health department offers robust services for this population from family planning and social support for young families to chronic illness care and behavioral health programs.",
                     description: "Only donations requested! They can help!",
                     url: URL (string:"https://goo.gl/maps/XWmS66P52RRx54Kx5")!),
        
        Organization( imageName: "volunteerhealthcare",
                     title: "Volunteer Healthcare Clinic",
                     typeOfOrganization: "Health Care",
                     hours: "Walk-In: Tuesday & Thursday evenings, CDA: Monday evenings, 3rd Wednesday at 6pm: Specialty Clinic ",
                     phoneNumber: "(512) 459-6002",
                     address: "4215 Medical Pkwy, Austin, TX 78756",
                     upcomingEvent: "Services provided include nurse and physician consultation and any related services such as lab testing, imaging services and prescriptions.",
                     description: "Only donations requested! They can help!",
                     url: URL (string:"https://goo.gl/maps/CDT7oUPX3xwbmFUm6")!),
        
        Organization( imageName: "salvationarmy",
                     title: "Salvation Army Homeless Clinic",
                     typeOfOrganization: "Health Care, Shelter",
                     hours: "Mon-Thurs: 8am-5am, Sun: 9am-12:30pm, Drive-thru food pantry on Saturdays, 9 – 11 AM.",
                     phoneNumber: "(512) 476-1111",
                     address: "501 E. 8th St. Austin, TX - 78701",
                     upcomingEvent: "This health center can cover services such as checkups, treatment, pregnancy care (where applicable), immunizations and child care (where applicable), prescription medicine and mental and substance abuse where applicable.",
                     description: "Contact them at the number provided for full details. They can help!",
                     url: URL (string:"https://goo.gl/maps/TBw1xCEELdYmRiHq6")!),
        
        Organization( imageName: "benwhite",
                     title: "Ben White Dental Clinic",
                     typeOfOrganization: "Health Care",
                     hours: "7:30 am to 6:00 pm, Monday-Friday",
                     phoneNumber: "(512) 978-9700",
                     address: "1221 W. Ben White, Austin, TX - 78704",
                     upcomingEvent: "Some services they include: Dental exams, teeth cleaning, fillings, extractions, dentures, emergency treatment, dental sealants, and more!",
                     description: "They can help! And it's free!",
                     url: URL (string:"https://goo.gl/maps/SYEaE2RFJdTybkq19")!),
        
        Organization( imageName: "rundberg",
                     title: "Rundberg Health Center",
                     typeOfOrganization: "Health Care",
                     hours: "Monday - Friday 7:10 am - 5:00 pm",
                     phoneNumber: "512-978-9600",
                     address: "825 E. Rundberg Lane, Ste. B-1 Austin, TX - 78753",
                     upcomingEvent: "This health center can cover services such as checkups, treatment, pregnancy care (where applicable), immunizations and child care (where applicable), prescription medicine and mental and substance abuse where applicable",
                     description: "They can help! And it's free!",
                     url: URL (string:"https://goo.gl/maps/L5Sc53phWkHhQnEw5")!),
        
        Organization( imageName: "travishealthcare",
                     title: "Travis County Healthcare: Central Health",
                     typeOfOrganization: "Health Care",
                     hours: "Mon-Fri: 8am-5pm, Sat-Sunday: Closed",
                     phoneNumber: "(512) 978-8000",
                     address: "1111 E. Cesar Chavez St. Austin, TX - 78702",
                     upcomingEvent: "This health center can cover services such as checkups, treatment, pregnancy care (where applicable), immunizations and child care (where applicable), prescription medicine and mental and substance abuse where applicable.",
                     description: "They can help! And it's free!",
                     url: URL (string:"https://g.page/CentralHealthTX?share")!),
        
        Organization( imageName: "benwhite",
                     title: "South Austin Health Center",
                     typeOfOrganization: "Health Care",
                     hours: "Mon-Fri: 8am-5pm, Sat-Sunday: Closed",
                     phoneNumber: "(512) 978-9500",
                     address: "2529 S. 1st St. Austin, TX - 78704",
                     upcomingEvent: "This health center can cover services such as checkups, treatment, pregnancy care (where applicable), immunizations and child care (where applicable), prescription medicine and mental and substance abuse where applicable.",
                     description: "They can help! And it's free!",
                     url: URL (string:"https://goo.gl/maps/3z8Stq5qkTwk8j2w6")!),
        
        Organization( imageName: "rbjdental",
                     title: "RBJ Dental Clinic",
                     typeOfOrganization: "Health Care",
                     hours: "Mon-Fri: 8am-12pm & 1pm-5pm, Sat-Sunday: Closed",
                     phoneNumber: "(512) 978-9895",
                     address: "15 Waller St. Austin, TX - 78702",
                     upcomingEvent: "Their services include dental exams, teeth cleaning, fillings, extractions, dentures, dental sealants, and emergency treatment.",
                     description: "They can help! And it's free!",
                     url: URL (string:"https://goo.gl/maps/3kYb2Wnan96rUfSA9")!),
        
        Organization( imageName: "eastaustin",
                     title: "East Austin Health Center",
                     typeOfOrganization: "Health Care",
                     hours: "Mon-Fri: 8am-5pm, Sat-Sunday: Closed",
                     phoneNumber: "(512) 978-9200",
                     address: "211 Comal St. Austin, TX - 78702",
                     upcomingEvent: "Services: Pediatrics, Women's Health, Maternity Care, Telepsychiatry (through videoconference)",
                     description: "They can help! And it's free!",
                     url: URL (string:"https://goo.gl/maps/vZSU6TszRSwMq4dT7")!),
        
        Organization( imageName: "northcentral",
                     title: "North Central Health Center",
                     typeOfOrganization: "Health Care",
                     hours: "Primary Care: Mon-Thurs: 7am-9pm, Fri: 7am-6pm, Sat: 8am-4:30pm",
                     phoneNumber: "(512) 978-9300",
                     address: "1210 W. Braker Lane Austin, TX - 78758",
                     upcomingEvent: "Services Offered: Dental including Pediatric Dentistry, Family Medicine, Internal Medicine, Pediatrics, Women's Health, Maternity Care, and others! ",
                     description: "They can help! And it's free!",
                     url: URL (string:"https://goo.gl/maps/HDKBKjrNp3n1UAMd8")!),

        
        Organization( imageName: "oakhill",
                     title: "Oak Hill Health Center",
                     typeOfOrganization: "Health Care",
                     hours: "Mon-Thurs: 7am-5pm, Fri: 8am-4pm, Sat-Sunday: Closed",
                     phoneNumber: "(512) 978-9820",
                     address: "8656-A Hwy 71 West, Austin, TX - 78735",
                     upcomingEvent: "Services: Family Medicine including children, Women's Health, & Maternity Care",
                     description: "They can help! And it's free!",
                     url: URL (string:"https://goo.gl/maps/b1t1bTVnJKCBHFB26")!),


        
        Organization( imageName: "foundation",
                         title: "Foundation For the Homeless",
                         typeOfOrganization: "Shelter",
                         hours: "Mon-Fri: 9am-5pm, Sat-Sun: Closed ",
                         phoneNumber: "(512) 453-6570",
                         address: "6719 N.Lamar Bld. Austin TX 78752",
                         upcomingEvent: "The Family Rehousing Initiative (FRI) program is a housing focused shelter and rapid rehousing program for families with children experiencing homelessness. ",
                         description: "Click the button to fill out the form or look at their website for more details:https://www.foundationhomeless.org/programs. They can help!",
                         url: URL (string:"https://g.page/ffhomeless?share")!),
            
        Organization( imageName: "arch",
                         title: "ARCH (Austin Resource Center for the Homeless)",
                         typeOfOrganization: "Clothing, Shelter, Health Care, Food",
                         hours: "Open 24 Hours",
                         phoneNumber: "512-978-9920",
                         address: "500 East 7th Street, Austin, TX 78701",
                         upcomingEvent: "Please check out their website or call for more details!",
                         description: "The ARCH is designed to assess client needs, provide information on how and where to access services, and meet the basic emergency needs of homeless adults.",
                         url: URL (string:"https://communitycaretx.org/locations/arch.html")!),
            
        Organization( imageName: "salvationarmy",
                         title: "Salvation Army Homeless Clinic",
                         typeOfOrganization: "Health Care, Shelter",
                         hours: "Mon-Thurs: 8am-5am, Sun: 9am-12:30pm, Drive-thru food pantry on Saturdays, 9 – 11 AM.",
                         phoneNumber: "(512) 476-1111",
                         address: "501 E. 8th St. Austin, TX - 78701",
                         upcomingEvent: "For those with no place to go or in need of emergency shelter, local Salvation Army homeless shelters provide a warm, safe place for men, women, and – whenever possible – families to stay.",
                         description: "Contact them at the number provided for full details. They can help!",
                         url: URL (string:"https://www.salvationarmyusa.org/usn/provide-shelter/")!),
            
        Organization( imageName: "safe",
                         title: "The SAFE Children's Shelter",
                         typeOfOrganization: "Shelter",
                         hours: "Mon - Fri: 8am-4pm",
                         phoneNumber: "(512) 267-7233",
                         address: " 4800 Manor Rd, Austin, TX 78723",
                         upcomingEvent: "Our shelter for children and young adults includes: Emergency care — emergency shelter for youth in the child protection system & Transitional living and supervised independent living — residential programs for young adults aging out of the foster care system ",
                         description: "Only donations requested! They can help!",
                         url: URL (string:"https://goo.gl/maps/4T7JJVRreyDH1dsF9")!),
            
        Organization( imageName: "casamarianella",
                         title: "Casa Marianella",
                         typeOfOrganization: "Shelter",
                         hours: "Please call us if you need help. ",
                         phoneNumber: "(512) 385-5571",
                         address: "821 Gunter St, Austin, TX 78702",
                         upcomingEvent: "Casa Marianella is an emergency homeless shelter that has served recently-arrived men and women immigrants, asylum seekers, and asylees since 1986 in East Austin.",
                         description: "Only donations requested! They can help!",
                         url: URL (string:"https://goo.gl/maps/cvqEq8dwic4Ei4B2A")!),
            
        Organization( imageName: "missionp",
                         title: "Mission Possible Austin: Church Under Bridge",
                         typeOfOrganization: "Shelter",
                         hours: "Sundays from 10:00am-2:00pm",
                         phoneNumber: "(512) 494-0953",
                         address: "Under I-35 Between 7th & 8th Street (1190 Chicon St, Austin, TX 78702)",
                         upcomingEvent: "At Church Under the Bridge, those who attend will have the opportunity to be a part of worship service every Sunday.his meal provides a great opportunity to connect and share a meal with all the individuals who call CUB their church home.",
                         description: "Join the Church Home with Mission Possible!",
                         url: URL (string:"https://goo.gl/maps/w5GnbU8wppLfhKzy7")!),
            
        Organization( imageName: "lifeworks",
                         title: "Lifeworks Austin",
                         typeOfOrganization: "Shelter",
                         hours: "Monday-Thursday 10AM-4PM.",
                         phoneNumber: "512-478-4939",
                         address: "3700 S 1st St, Austin, TX 78704",
                         upcomingEvent: "LifeWorks provides housing along with other services and programming that youth experiencing homelessness need to live independently and self‑sufficiently. ",
                         description: "They can help!",
                         url: URL (string:"https://goo.gl/maps/YDw891HJd3bz5wbZ7")!),
            
        Organization( imageName: "caritas",
                         title: "Caritas of Austin",
                         typeOfOrganization: "Shelter",
                         hours: "Mon-Wed: 8am-4:40pm, Tues: 8am-6:40pm, Fri: 8am-11:45am, Sat-Sun: Closed",
                         phoneNumber: "(512) 479-4610",
                         address: "1212 W Ben White Blvd, Austin, TX 78704",
                         upcomingEvent: "Caritas of Austin’s Permanent Supportive Housing program provides housing, onsite supportive services, and mental health counseling for disabled individuals experiencing long-term homelessness",
                         description: "They can help!",
                         url: URL (string:"https://goo.gl/maps/PXAwzfSAhnVhbgcZA")!),
            
        Organization( imageName: "frontsteps",
                         title: "Front Steps",
                         typeOfOrganization: "Shelter",
                         hours: "Open 24 Hours.",
                         phoneNumber: "(512) 305-4100",
                         address: "500 E 7th St, Austin, TX 78701",
                         upcomingEvent: "It offers emergency shelter, basic services and connections to housing for 130 men.",
                         description: "Only shelter for men. They can help!",
                         url: URL (string:"https://goo.gl/maps/BDL6sQVk43sLVzex6")!),
            
        Organization( imageName: "salvationarmy",
                         title: "Austin Shelter for Women and Children ",
                         typeOfOrganization: "Shelter",
                         hours: "Open 24 Hours. ",
                         phoneNumber: "(512) 933-0600",
                         address: " 4613 Tannehill Ln Bldg 3, Austin, TX 78721",
                         upcomingEvent: "The emergency shelter serves single adult women and women and their dependents. Services include case management, job training, and housing location.",
                         description: "Only for women and children. They can help!",
                         url: URL (string:"https://g.page/ASWC_TSA?share")!),
        
        Organization( imageName: "salvationarmy",
                     title: "Rathgeber Center for Families",
                     typeOfOrganization: "Shelter",
                     hours: "Open 24 Hours. ",
                     phoneNumber: "(512) 933-0600",
                     address: " 4613 Tannehill Ln Bldg 3, Austin, TX 78721",
                     upcomingEvent: "Our services help families move from homelessness to stable housing, confidence, and self-sufficiency",
                     description: "They can help!",
                     url: URL (string:"https://goo.gl/maps/zDPsk7kaZSXgYYHLA")!),
        
        Organization( imageName: "greendoors",
                     title: "Greendoors ",
                     typeOfOrganization: "Shelter",
                     hours: "Mon-Fri: 9am-5pm, Sat-Sun: Closed  ",
                     phoneNumber: "(512) 469-9130",
                     address: "1503 S IH 35 Frontage Rd, Austin, TX 78741",
                     upcomingEvent: "This organization offers transitional and afforable permanent housing for individuals.",
                     description: "They can help!",
                     url: URL (string:"https://goo.gl/maps/myBZSFe3WSSA3dv7A")!),
        
        Organization( imageName: "blackland",
                     title: "Blackland Affordable Housing Program",
                     typeOfOrganization: "Shelter",
                     hours: " For the latest information on our housing and waitlists, please call us at 512-220-8751 and select option 1.",
                     phoneNumber: " (512) 220-8751",
                     address: "1902 E 22nd St, Austin, TX 78722",
                     upcomingEvent: "Blackland Community Development Corporation (BCDC) provides targeted affordable and supportive housing to low-income families and homeless individuals in the Blackland neighborhood of East Austin. ",
                     description: "They can help!",
                     url: URL (string:"https://goo.gl/maps/1ebY458Y9WskDJdFA")!),
        
        Organization( imageName: "salvationarmy",
                     title: "The Salvation Army Downtown Center",
                     typeOfOrganization: "Shelter",
                     hours: "Mon-Fri: 8am-4:30pm, Sat-Sun: Closed",
                     phoneNumber: "(512) 476-1111",
                     address: " 501 E 8th St, Austin, TX 78701",
                     upcomingEvent: "The Salvation Army Social Services Center (SSC), built in 1987, is a low barrier, housing focused emergency shelter providing 242 beds currently for individual men and women experiencing homelessness.",
                     description: " They can help!",
                     url: URL (string:"https://goo.gl/maps/GFTzfCVx6JMJMHiPA/")!),
        
        Organization( imageName: "trinity",
                     title: "Trinity Center",
                     typeOfOrganization: "Food",
                     hours: "Serving boxed breakfasts curbside Mon-Friday starting at 9amfor first 80 people. Suday meal at 3 p.m. for first 65 people.",
                     phoneNumber: "512-610-3559",
                     address: "304 E. 7th Austin, TX 78701",
                     upcomingEvent: "Show up at the hours given for a hot meal!",
                     description: "Please call if you need help! They can provide for you!",
                     url: URL (string:"https://goo.gl/maps/9FQwHfKShDVV3aS49")!),
        
        
        Organization( imageName: "hopefood",
                     title: "Hope Food Pantry Austin",
                     typeOfOrganization: "Food",
                     hours: "Every Thursday and Friday, and the first Saturday of the month, between 9-10:30am ",
                     phoneNumber: "(512) 592-3171",
                     address: "4001 Speedway, Austin, TX 78751",
                     upcomingEvent: "Everyone in need of groceries is welcome!",
                     description: "They can help! Please reach out!",
                     url: URL (string:"https://goo.gl/maps/WvX3H1dxybnuHcJ37")!),
        
        
        Organization( imageName: "feedingtexas",
                     title: "Feeding Texas",
                     typeOfOrganization: "Food",
                     hours: "Mon-Thurs: 8:30am-5pm, Fri: 9am-3pm, Sat-Sun: Closed",
                     phoneNumber: "(512) 527-3613",
                     address: "1524 S IH 35 Frontage Rd #342, Austin, TX 78704",
                     upcomingEvent: "Sign up for nutrition benefits like SNAP (food stamps), Find free groceries, and Connect to other helpful services",
                     description: "Please use the link to the website! It can help.",
                     url: URL (string:"https://goo.gl/maps/1pwCdZvpiYWFYieFA")!),
        
        Organization( imageName: "feedmypeople",
                     title: "Feed My People (FMP)-Homeless Breakfast",
                     typeOfOrganization: "Food",
                     hours: "Tuesdays and Thursdays from 5:30-7:00 a.m",
                     phoneNumber: "(512) 478-5684",
                     address: "1201 Lavaca St, Austin, TX 78701",
                     upcomingEvent: "Feed My People Breakfast to Go: They are serving a sack breakfast at the door of the Family Life Center!",
                     description: "They can help!",
                     url: URL (string:"https://goo.gl/maps/CnKWdVLcQ3oGS9kN7")!),
        
        Organization( imageName: "angelhouse",
                     title: "Angel House Soup Kitchen",
                     typeOfOrganization: "Food",
                     hours: "Everyday: Breakfast 9:30-10:00am; Lunch 11:00am-12:30pm",
                     phoneNumber: "(512) 643-2327",
                     address: "908 E Cesar Chavez St, Austin, TX 78702",
                     upcomingEvent: "Although we are not a food pantry ,we are a soup kitchen  that serves a hot meal every day for our guests.",
                     description: "They give hot meals everyday! They can help!",
                     url: URL (string:"https://goo.gl/maps/LHZB8qZqTHsZWJzP7")!),
        
        Organization( imageName: "mosaicchurch",
                     title: "Mosaic Church",
                     typeOfOrganization: "Food, Clothing",
                     hours: "Sunday morning from 9am-11am",
                     phoneNumber: "(512) 537-0027",
                     address: "12675 Research Blvd, Austin, TX 78759",
                     upcomingEvent: "Our Sunday morning care team serves breakfast and coffee, takes and fills orders for clothing and other items, listens to needs, prays for people, and develops relationships with our homeless friends",
                     description: "They can help!.",
                     url: URL (string:"https://goo.gl/maps/k7mCNXAXp79s1GJEA")!),
        
        Organization( imageName: "mobile",
                     title: "Mobile Loaves and Fishing",
                     typeOfOrganization: "Food",
                     hours: "Loook at their truck schedules for the stops.",
                     phoneNumber: "(512) 328-7299",
                     address: "Address: 9301 Hog Eye Rd #950, Austin, TX 78724",
                     upcomingEvent: "The truck stops tell the meal delivery location.",
                     description: "Press the button below to see the schedule! They can help!",
                     url: URL (string:"https://goo.gl/maps/xajZ3U1JGLfmjNXP8")!),
        
        Organization( imageName: "rebekahbaines",
                     title: "Senior 55+ Only: Rebekah Baines Johnson Center",
                     typeOfOrganization: "Food",
                     hours: "3rd Wednesday 9am-11am (For seniors 55+ only)",
                     phoneNumber: "512) 476-6051",
                     address: "21 Waller St Austin, TX 78702",
                     upcomingEvent: "Senior Only Food Pantry and other HOPE services.",
                     description: "If you're 55+, please go! They can help!",
                     url: URL (string:"http://www.rbjseniorhousing.org/resources.html")!),
        
        Organization( imageName: "ourlady",
                     title: "Our Lady of Guadalupe Church",
                     typeOfOrganization: "Food",
                     hours: "Fri: 11:30am-1:30pm (not the 3rd Fri, 3rd Saturdays 10am-12pm",
                     phoneNumber: "512-478-7955",
                     address: "1206 East 9th Street Austin, TX 78702",
                     upcomingEvent: "There is a food pantry open during those hours!",
                     description: "Please go if you need help!",
                     url: URL (string:"https://goo.gl/maps/iwJFvSf86Si1CnEd7")!),
        
        Organization( imageName: "eastaustin",
                     title: "East Austin Neighborhood Center",
                     typeOfOrganization: "Food",
                     hours: "You can call this neighborhood center for an appointment from Mon-Thurs:8am-6pm and Fri: 8am-12pm",
                     phoneNumber: "512-972-6650",
                     address: "211 Comal St Austin, TX 78702",
                     upcomingEvent: "The food pantry is open by APPOINTMENT, so call ahead to arrange a curbside pick-up or request special accommodations.",
                     description: "Each household can get food once per month!",
                     url: URL (string:"https://goo.gl/maps/yqJcp2oM1J8z8aYu8")!),

    ]
}
    


